project:
  type: website
  output-dir: _site
  preview:
    port: 4200
    browser: false

website:
  title: "Burk (2024) Survival Benchmark"
  reader-mode: true
  repo-url: https://github.com/slds-lmu/paper_2023_survival_benchmark
  repo-actions: [issue]
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: results.qmd
        text: Results
      - href: metadata.qmd
        text: Models, Data, Measures
    right:
      - href: https://github.com/slds-lmu/paper_2023_survival_benchmark
        icon: github
  # page-footer:
  #   left: "Copyright 2021, Norah Jones"
  #   right:
  #     - icon: github
  #       href: https://github.com/

format:
  html:
    code-fold: true
    toc: true
    # toc-expand: 2
    toc-depth: 4
    toc-location: left
    embed-resources: false
    fig-align: center
    number-sections: true
    theme:
      light: flatly
      dark: darkly
lightbox: true


execute:
  cache: true
  freeze: auto  # re-render only when source changes
