---
title: "A Large-Scale Neutral Comparison Study of Survival Models on Low-Dimensional Data"
author: "Lukas Burk, John Zobolas, Bernd Bischl, Andreas Bender, Marvin N. Wright, Raphael Sonabend"
date: "today"
---

This site aggregates additional results and metadata accompanying the benchmark project.

All code is available on [GitHub at slds-lmu/paper_2023_survival_benchmark](https://github.com/slds-lmu/paper_2023_survival_benchmark).

## Downloading Results

Results can be downloaded from the web at [projects.lukasburk.de/survival_benchmark/results](https://projects.lukasburk.de/survival_benchmark/results/).
The files required to produce primary results

The most important files are:

| File | Description |
|------|-------------|
| `aggr_scores.[csv|rds]` | Scores for all learners, tasks and measures aggregated across outer resampling iterations |
| `scores.[csv|rds]` | Scores for all learners, tasks and measures for individual outer resampling iterations |
| `archives.zip` | ZIP file of all tuning archives produced during the benchmark (over 4000) in CSV files for each combination of learner, task, tuning measure, and resampling iteration |


Folder `harrell_c` and `rcll` contain the individual files from with `aggr_scores` and `scores` are created and are therefore only an intermediate product.
Similarly, files starting with `bmr_` (`BenchmarkResult`) or `bma_` (`BenchmarkAggr`) are intermediate results and are only relevant if these `mlr3` objects are specifically required.

## Measure Glossary

The following table provides a brief overview of the measures used in this benchmark.
Unfortunately, during early benchmark development slightly different shorthand names were used for the measures in filenames for result files than the abbreviations used in the paper.

- `id` refers to the shorthand used in the result files listed above.
- `mlr_id` refers to the measure as it is implemented in [mlr3proba](https://mlr3proba.mlr-org.com/reference/index.html#survival-measures)
- `Label` refers to the measure as it is named consistently throughout the paper and resulting plots.

| id                   | mlr3 id            | Label                                                        |
|:---------------------|:-------------------|:-------------------------------------------------------------|
| `harrell_c`          | `surv.cindex`      | Harrell's C                                                  |
| `uno_c`              | `surv.cindex`      | Uno's C                                                      |
| `rcll`               | `surv.rcll`        | Right-Censored Log Loss (RCLL)                               |
| `rcll_erv`           | `surv.rcll`        | Right-Censored Log Loss (RCLL) [ERV]                         |
| `intlogloss`         | `surv.intlogloss`  | Re-weighted Integrated Survival Log-Likelihood (RISLL)       |
| `intlogloss_erv`     | `surv.intlogloss`  | Re-weighted Integrated Survival Log-Likelihood (RISLL) [ERV] |
| `logloss`            | `surv.logloss`     | Re-weighted Negative Log-Likelihood (RNLL)                   |
| `logloss_erv`        | `surv.logloss`     | Re-weighted Negative Log-Likelihood (RNLL) [ERV]             |
| `brier_improper`     | `surv.brier`       | Integrated Survival Brier Score (ISBS)                       |
| `brier_improper_erv` | `surv.brier`       | Integrated Survival Brier Score (ISBS) [ERV]                 |
| `dcalib`             | `surv.dcalib`      | D-Calibration                                                |
| `caliba_ratio`       | `surv.calib_alpha` | Van Houwelingen's Alpha                                      |
