---
title: 'Task: Factors'
author: "Lukas Burk"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(dplyr)
library(data.table)
library(kableExtra)
```

## Overview 

```{r}
# Checking datasets for low factor level counts

overview <- purrr::map_df(fs::dir_ls(here::here("datasets"), glob = "*rds"), ~{
  tmpds <- readRDS(.x)

  tibble::tibble(
    dataset = fs::path_file(.x) |> stringr::str_remove("\\.rds"),
    N = nrow(tmpds),
    N_events = sum(tmpds$status),
    n_features = ncol(tmpds) - 2,
    n_factor_vars = sum(purrr::map_lgl(tmpds, is.factor))
  )
})

overview |>
  arrange(desc(N)) |>
  kbl() |>
  kable_styling()
```

Tasks with factors: **`r sum(overview$n_factor_vars > 0)`**

```{r, results='asis'}
tasks <- purrr::map(fs::dir_ls(here::here("datasets"), glob = "*rds"), function(x) {
  data.table(readRDS(x))
})

names(tasks) <- names(tasks) |>
  fs::path_file() |>
  fs::path_ext_remove()

for (task in names(tasks)) {
  xdat <- tasks[[task]]
  n <- nrow(xdat)
  fact_vars <- purrr::map_lgl(xdat, is.factor)

  if (sum(fact_vars) == 0) next

  cat(glue::glue("### Task '{task}' (N = {nrow(xdat)}):\n\n"))

  rbindlist(lapply(names(fact_vars[fact_vars]), function(var) {

    fctbl <- xdat[, .(nl = .N), by = var]
    fctbl <- fctbl[, prop := round(100 * nl/n, 2)]
    setorder(fctbl, nl)[]
    fctbl <- melt(fctbl, measure.vars = var)
    setcolorder(fctbl, c("variable", "value", "nl", "prop"))
    fctbl[]
  })) |>
    mutate(
      nl = ifelse(nl < 20, cell_spec(nl, color = "red"), nl)
    ) |>
    kbl(
      caption = "Factor levels for each variable with proportion relative to full task",
      col.names = c("Variable", "Factor Level", "n", "%"),
      escape = FALSE
    ) |>
    kable_styling() |>
    collapse_rows(columns = 1) |>
    print()
  
  cat("\n\n")
}


```

## Also counting by `status`

```{r}
alltbl <- rbindlist(lapply(names(tasks), function(task) {
  xdat <- tasks[[task]]
  n <- nrow(xdat)
  fact_vars <- purrr::map_lgl(xdat, is.factor)
  if (sum(fact_vars) == 0) return(data.table())
  
  res <- rbindlist(lapply(names(fact_vars[fact_vars]), function(var) {
    fctbl <- xdat[, .(nl = .N), by = c(var, "status")] |>
      tidyr::complete(.data[[var]], status, fill = list(nl = 0))
    data.table::setDT(fctbl)
    fctbl <- fctbl[, prop := round(100 * nl/n, 2)]
    setorder(fctbl, nl)[]
    fctbl <- melt(fctbl, measure.vars = var)
    fctbl[, nl := ifelse(nl < 20, cell_spec(nl, color = "red"), nl)]
  }))
  res[, task := task]
  setcolorder(res, c("task", "variable", "status", "value", "nl", "prop"))

}))

alltbl |>
  dplyr::mutate(value = stringr::str_replace(value, pattern = "<", "&lt;")) |>
    kbl(
      caption = "Factor levels for each variable with proportion relative to full task",
      col.names = c("Task", "Variable", "Status", "Factor Level", "n", "%"),
      escape = FALSE
    ) |>
    kable_styling(bootstrap_options = c("striped", "hover"))
    #collapse_rows(columns = c(1, 2, 3))
```

