---
title: "Status"
author: "Lukas Burk"
date: "`r Sys.Date()`"
output: 
  html_document: 
    toc: yes
    toc_float: yes
    fig_width: 9
    fig_height: 6
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

root = here::here()
cli::cli_alert_info("Loading config \"{Sys.getenv('R_CONFIG_ACTIVE', 'default')}\"")
settings = config::get()

source(file.path(root, "helpers.R"))

library("batchtools")
library(kableExtra)
# Assumes batchmark.R is run beforehand
reg_dir = file.path(root, settings$reg_name)
reg = loadRegistry(reg_dir, writeable = FALSE)

tablify = function(x) {
  x |>
    kbl() |>
    kable_styling(bootstrap_options = c("striped", "hover")) |>
    group_rows(table(x[[1]]))
}
```

# Univariate

## Tuning Measure

```{r}
check_job_state(byvars = "measure") |>
  tablify()

```

## Learner

```{r}
check_job_state(byvars = "learner_id") |>
  tablify()
```

## Task

```{r}
check_job_state(byvars = "task_id") |>
  tablify()
```

# Bivariate

## Tuning Measure x Learner

```{r}
check_job_state(byvars = c("measure", "learner_id")) |>
    tablify()
```

## Tuning Measure x Task

```{r}
check_job_state(byvars = c("measure", "task_id")) |>
  tablify()
```

## Learner x Task

```{r}
check_job_state(byvars = c("learner_id", "task_id")) |>
  tablify()
```

## Task x Learner

```{r}
check_job_state(byvars = c("task_id", "learner_id")) |>
  tablify()
```

